-- MINE.MPP_CASH_INP_SUB definition

CREATE TABLE "MINE"."MPP_CASH_INP_SUB"
(	"SERIAL_NO" VARCHAR2(50),
     "EMP_ID" VARCHAR2(20),
     "EMP_NAME" VARCHAR2(100),
     "PREV_DAY_ADV_RECEIPT" NUMBER(18,2),
     "TODAY_ADV_PAYMENT" NUMBER(18,2),
     "TODAY_SETTLE_INCOME" NUMBER(18,2),
     "TODAY_PRE_HOSP_INCOME" NUMBER(18,2),
     "TRAFFIC_ASSIST_FUND" NUMBER(18,2),
     "BLOOD_DONATE_COMPENSATE" NUMBER(18,2),
     "RECEIVABLE_PAYABLE" NUMBER(18,2),
     "TODAY_REPORT_TOTAL" NUMBER(18,2),
     "PREV_DAY_IOU" NUMBER(18,2),
     "TODAY_OUTP_IOU" NUMBER(18,2),
     "TODAY_REPORT_REC_PAY" NUMBER(18,2),
     "TODAY_ADV_RECEIPT" NUMBER(18,2),
     "TODAY_REPORT_CASH_RCV" NUMBER(18,2),
     "TODAY_CASH_RCV_TOTAL" NUMBER(18,2),
     "BALANCE" NUMBER(18,2),
     "ADJUSTMENT" NUMBER(18,2),
     "TODAY_IOU" NUMBER(18,2),
     "HOLIDAY_PAYMENT" NUMBER(18,2),
     "CASH_ON_HAND" NUMBER(18,2),
     "DIFFERENCE" NUMBER(18,2),
     "REMARKS" VARCHAR2(500),
     "CREATED_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     "UPDATED_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
     "CREATED_BY" VARCHAR2(50),
     "UPDATED_BY" VARCHAR2(50),
     PRIMARY KEY ("SERIAL_NO")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MINE"."SYS_C0011686" ON "MINE"."MPP_CASH_INP_SUB" ("SERIAL_NO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

COMMENT ON TABLE MINE.MPP_CASH_INP_SUB IS '住院现金统计子表';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.SERIAL_NO IS '主键ID/流水号';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.EMP_ID IS '收费员ID';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.EMP_NAME IS '收费员姓名';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.PREV_DAY_ADV_RECEIPT IS '前日暂收款';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_ADV_PAYMENT IS '今日预交金数';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_SETTLE_INCOME IS '今日结账收入';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_PRE_HOSP_INCOME IS '今日院前收入';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TRAFFIC_ASSIST_FUND IS '交通救助金';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.BLOOD_DONATE_COMPENSATE IS '无偿献血补偿金';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.RECEIVABLE_PAYABLE IS '应收款/应付款';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_REPORT_TOTAL IS '今日报表数合计';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.PREV_DAY_IOU IS '前日欠条';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_OUTP_IOU IS '今日门诊借条';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_REPORT_REC_PAY IS '今日报表应收/应付';


COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_ADV_RECEIPT IS '今日暂收款';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_REPORT_CASH_RCV IS '今日报表实收';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_CASH_RCV_TOTAL IS '今日实收现金合计';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.BALANCE IS '余额';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.ADJUSTMENT IS '调整';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.TODAY_IOU IS '今日欠条';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.HOLIDAY_PAYMENT IS '节假日交款';

COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.CASH_ON_HAND IS '库存现金';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.DIFFERENCE IS '差额';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.REMARKS IS '备注';

COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.UPDATED_TIME IS '更新时间';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.CREATED_BY IS '创建人';
COMMENT ON COLUMN MINE.MPP_CASH_INP_SUB.UPDATED_BY IS '更新人';