spring.application.name=auto_demo
server.port=18888
browser.port=9223

yb.export.isOpenExportInterface =true 
yb.export.isSaveExcel =false
yb.export.url=http://mas.cq.hsip.gov.cn/hds/back/web/gatherNetInfoByDay/exportAllSetlInfo


yb.insutype=310,390,515253,3101,3901
yb.insutype.cn=\u804c\u5de5\u57fa\u672c\u533b\u7597\u4fdd\u9669,\u57ce\u4e61\u5c45\u6c11\u57fa\u672c\u533b\u7597\u4fdd\u9669,\u751f\u80b2\u533b\u7597\u4fdd\u9669,\u5f02\u5730\u804c\u5de5\u57fa\u672c\u533b\u7597\u4fdd\u9669,\u5f02\u5730\u5c45\u6c11\u57fa\u672c\u533b\u7597\u4fdd\u9669


yb.bill.url=http://mas.cq.hsip.gov.cn/hds/back/web/gatherNetInfoByDay/queryMedinsGatherNetInfoByDay
yb.setl.url=http://mas.cq.hsip.gov.cn/hds/back/web/psnSetlPrint/querySetlPageInfoPayLoc
yb.frontSetlUrl=http://mas.cq.hsip.gov.cn/hds/N1702.html#/N170204?_modulePartId_=17-2-4

yb.token=54a01b7b-98a3-4c8c-9d05-38a6db76f5bd
yb.session=YWNhYjgzN2YtNDAxYS00YWZkLWJjYWItMzdiMzk2ZTc3YjA3
yb.pageSize=10000
yb.frontUrl=http://mas.cq.hsip.gov.cn/hds/N1703.html#/N170301?pageKey=1
yb.fixmedinsCode=H50010606446