-- ============================================================
-- 门诊财务报表 TR_OUTP_FIN_* 表/字段注释补齐
-- 适用: 表已按旧版DDL建好, 只需补注释, 无需删表重建
-- ============================================================

-- TR_OUTP_FIN_CLINIC_MASTER 门诊挂号明细(← clinic_master)
COMMENT ON TABLE  TR_OUTP_FIN_CLINIC_MASTER IS '门诊财务报表-就诊主表日快照';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.PATIENT_ID IS '病人ID';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.STAT_DATE IS '统计日期(所有查询的过滤列)';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.VISIT_DATE IS '就诊日期';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.VISIT_NO IS '就诊号(关联 MOP_QUEUE 取号渠道)';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.RETURNED_DATE IS '退号日期';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.IS_RETURN_TYPE IS '是否退号(1=收/汇总口径，-1=退口径，进项=当日全部)';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.REGISTRATION_STATUS IS '挂号状态(0=作废/无效；非0=有效。退项过滤用 <>0)';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.REGIST_FEE IS '挂号费';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.CLINIC_FEE IS '诊查费';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.CLINIC_LABEL IS '科室/号源标签';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.VISIT_TIME_DESC IS '就诊时段';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.OPERATOR_NO IS '操作员工号';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.CREATE_TIME IS '数据创建时间';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.UPDATE_TIME IS '数据更新时间';

-- TR_OUTP_FIN_RCPT_ACCT 门诊收据明细(← outp_rcpt_master)
COMMENT ON TABLE  TR_OUTP_FIN_RCPT_ACCT IS '门诊财务报表-收据明细(人次去重、渠道/支付方式/业务类型分析)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.RCPT_NO IS '收据号(人次去重解析前缀+序号、关联支付表)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.PATIENT_ID IS '患者ID(人次去重)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.STAT_DATE IS '统计日期(所有查询的过滤列)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.VISIT_DATE IS '就诊日期';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.TOTAL_CHARGES IS '金额(缴费人次进项/退项判定)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.TOTAL_COSTS IS '金额(业务类型金额口径)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.REFUNDED_RCPT_NO IS '退费关联收据号(退项筛选)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.OPERATOR_NO IS '操作员号(渠道归类)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.BILL_CLASS IS '单据类别(业务类型分界后挂号/缴费判定)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.CREATE_TIME IS '数据创建时间';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.UPDATE_TIME IS '数据更新时间';

-- TR_OUTP_FIN_ACCT_MASTER 门诊结账汇总(← outp_acct_master, 收据张数/金额唯一口径)
COMMENT ON TABLE  TR_OUTP_FIN_ACCT_MASTER IS '门诊财务报表-结账汇总(收据张数/金额唯一口径)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.ACCT_NO IS '结账号(关联结账支付方式明细)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.ACCT_DATE IS '结账日期';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.STAT_DATE IS '统计日期(所有查询的过滤列)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.OPERATOR_NO IS '收费员号(渠道分析)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.TOTAL_COSTS IS '总费用(进项金额)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.TOTAL_INCOMES IS '收入金额(汇总金额)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.REFUND_AMOUNT IS '退费金额(退项金额)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.RCPTS_NUM IS '收据张数(进项)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.REFUND_NUM IS '退费张数(汇总从张数里扣减、退项)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.FREE_OF_CHARGE_NUM IS '免费票张数(仅留存,报表口径不再使用)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.CREATE_TIME IS '数据创建时间';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.UPDATE_TIME IS '数据更新时间';

-- TR_OUTP_FIN_PAYMENTS_MONEY 门诊支付明细(← outp_payments_money, 无日期列需JOIN收据补)
COMMENT ON TABLE  TR_OUTP_FIN_PAYMENTS_MONEY IS '门诊财务报表-支付方式明细';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.RCPT_NO IS '关联收据号(JOIN收据明细取日期/患者)';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.MONEY_TYPE IS '支付方式(应收/实收分类)';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.PAYMENT_AMOUNT IS '实收金额';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.REFUNDED_AMOUNT IS '退费金额';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.CREATE_TIME IS '数据创建时间';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.UPDATE_TIME IS '数据更新时间';

-- TR_OUTP_FIN_MOP_QUEUE 排班队列(← cq_card.mop_timeschedule_queue, 订单来源分析用)
COMMENT ON TABLE  TR_OUTP_FIN_MOP_QUEUE IS '门诊财务报表-排班队列(订单来源分析)';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.SCHEDULE_ID IS '排班ID';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.PATIENT_ID IS '患者ID';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.STAT_DATE IS '统计日期(与挂号明细同日关联)';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.VISIT_NO IS '就诊号(与挂号明细关联)';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.SOURCE_NAME IS '取号来源名称(订单来源分析)';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.QUEUE_TYPE IS '队列类型';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.IS_USED IS '是否使用';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.VISIT_DATE IS '就诊日期';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.CREATE_TIME IS '数据创建时间';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.UPDATE_TIME IS '数据更新时间';

-- TR_OUTP_FIN_ACCT_MONEY 结账支付方式明细(← outp_acct_money)
COMMENT ON TABLE  TR_OUTP_FIN_ACCT_MONEY IS '门诊财务报表-结账支付方式明细';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MONEY.ACCT_NO IS '结账号(关联结账汇总)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MONEY.MONEY_TYPE IS '支付方式';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MONEY.INCOME_AMOUNT IS '收入金额';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MONEY.REFUNDED_AMOUNT IS '退费金额';
