-- ============================================================
-- 门诊财务报表 ETL 存储表 (powerihsp schema)
-- ============================================================

-- 清理已存在对象(如重建请先执行)
DROP TABLE TR_OUTP_FIN_CLINIC_MASTER CASCADE CONSTRAINTS;
DROP TABLE TR_OUTP_FIN_RCPT_ACCT CASCADE CONSTRAINTS;
DROP TABLE TR_OUTP_FIN_ACCT_MASTER CASCADE CONSTRAINTS;
DROP TABLE TR_OUTP_FIN_PAYMENTS_MONEY CASCADE CONSTRAINTS;
DROP TABLE TR_OUTP_FIN_MOP_QUEUE CASCADE CONSTRAINTS;
DROP TABLE TR_OUTP_FIN_ACCT_MONEY CASCADE CONSTRAINTS;
-- 1. TR_OUTP_FIN_CLINIC_MASTER - 门诊挂号明细（← clinic_master）
CREATE TABLE TR_OUTP_FIN_CLINIC_MASTER (
    ID                  NUMBER(19) PRIMARY KEY,
    PATIENT_ID          VARCHAR2(64),
    STAT_DATE           DATE,
    VISIT_DATE          DATE,
    VISIT_NO            VARCHAR2(64),
    RETURNED_DATE       DATE,
    IS_RETURN_TYPE      NUMBER(1),
    REGIST_FEE          NUMBER(18,2),
    CLINIC_FEE          NUMBER(18,2),
    CLINIC_LABEL        VARCHAR2(100),
    VISIT_TIME_DESC     VARCHAR2(100),
    OPERATOR_NO         VARCHAR2(20),
    CREATE_TIME         DATE DEFAULT SYSDATE,
    UPDATE_TIME         DATE DEFAULT SYSDATE
);
-- 2. TR_OUTP_FIN_RCPT_ACCT - 门诊收据明细（← outp_rcpt_master）
CREATE TABLE TR_OUTP_FIN_RCPT_ACCT (
    ID                  NUMBER(19) PRIMARY KEY,
    RCPT_NO             VARCHAR2(64) NOT NULL,
    PATIENT_ID          VARCHAR2(64),
    STAT_DATE           DATE,
    VISIT_DATE          DATE,
    TOTAL_CHARGES       NUMBER(18,2),
    TOTAL_COSTS         NUMBER(18,2),
    REFUNDED_RCPT_NO    VARCHAR2(64),
    OPERATOR_NO         VARCHAR2(20),
    BILL_CLASS          VARCHAR2(10),
    CREATE_TIME         DATE DEFAULT SYSDATE,
    UPDATE_TIME         DATE DEFAULT SYSDATE
);
-- 3. TR_OUTP_FIN_ACCT_MASTER - 门诊结账汇总（← outp_acct_master，收据张数/金额唯一口径）
CREATE TABLE TR_OUTP_FIN_ACCT_MASTER (
    ID                  NUMBER(19) PRIMARY KEY,
    ACCT_NO             VARCHAR2(64),
    ACCT_DATE           DATE,
    STAT_DATE           DATE,
    OPERATOR_NO         VARCHAR2(20),
    TOTAL_COSTS         NUMBER(18,2),
    REFUND_AMOUNT       NUMBER(18,2),
    RCPTS_NUM           NUMBER(12),
    REFUND_NUM          NUMBER(12),
    CREATE_TIME         DATE DEFAULT SYSDATE,
    UPDATE_TIME         DATE DEFAULT SYSDATE
);
-- 4. TR_OUTP_FIN_PAYMENTS_MONEY - 门诊支付明细（← outp_payments_money，无日期列需JOIN补）
CREATE TABLE TR_OUTP_FIN_PAYMENTS_MONEY (
    ID                  NUMBER(19) PRIMARY KEY,
    RCPT_NO             VARCHAR2(64) NOT NULL,
    MONEY_TYPE          VARCHAR2(30),
    PAYMENT_AMOUNT      NUMBER(18,2),
    REFUNDED_AMOUNT     NUMBER(18,2),
    CREATE_TIME         DATE DEFAULT SYSDATE,
    UPDATE_TIME         DATE DEFAULT SYSDATE
);
-- 5. TR_OUTP_FIN_MOP_QUEUE - 排班队列（← cq_card.mop_timeschedule_queue，仅bt2用）
CREATE TABLE TR_OUTP_FIN_MOP_QUEUE (
    ID                  NUMBER(19) PRIMARY KEY,
    SCHEDULE_ID         VARCHAR2(100),
    PATIENT_ID          VARCHAR2(64),
    STAT_DATE           DATE,
    VISIT_NO            VARCHAR2(64),
    SOURCE_NAME         VARCHAR2(100),
    QUEUE_TYPE          VARCHAR2(20),
    IS_USED             VARCHAR2(20),
    VISIT_DATE          DATE,
    CREATE_TIME         DATE DEFAULT SYSDATE,
    UPDATE_TIME         DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.ID IS '主键ID';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.PATIENT_ID IS '病人ID';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.VISIT_DATE IS '就诊日期';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.RETURNED_DATE IS '退号日期';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.REGIST_FEE IS '挂号费';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.CLINIC_FEE IS '诊查费';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.CLINIC_LABEL IS '科室/号源标签';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.VISIT_TIME_DESC IS '就诊时段';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.OPERATOR_NO IS '操作员工号';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.CREATE_TIME IS '数据创建时间';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.UPDATE_TIME IS '数据更新时间';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.ID IS '主键ID';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.RCPT_NO IS '收据号（人次去重解析前缀+序号、关联支付表）';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.PATIENT_ID IS '患者ID（人次去重）';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.VISIT_DATE IS '就诊日期';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.TOTAL_CHARGES IS '金额（bt6渠道金额、bt8业务类型金额）';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.REFUNDED_RCPT_NO IS '退费关联收据号（退项T3筛选）';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.OPERATOR_NO IS '操作员号（bt1/3/4/6归类）';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.BILL_CLASS IS '单据类别（bt8分界后挂号/缴费判定）';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.ID IS '主键ID';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.ACCT_DATE IS '结账日期';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.TOTAL_COSTS IS '总费用（T1金额）';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.REFUND_AMOUNT IS '退费金额（T3金额）';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.RCPTS_NUM IS '收据张数（T1）';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.REFUND_NUM IS '退费张数（T3）';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.ID IS '主键ID';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.RCPT_NO IS '关联收据号（JOIN RCPT_ACCT取patient_id/visit_date）';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.MONEY_TYPE IS '支付方式（bt5/7/9类别）';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.PAYMENT_AMOUNT IS '实收金额（bt7/9）';
COMMENT ON COLUMN TR_OUTP_FIN_PAYMENTS_MONEY.REFUNDED_AMOUNT IS '退费金额（bt7/9）';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.ID IS '主键ID';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.SCHEDULE_ID IS '排班ID（与clinic_label|yyyyMMdd|visit_time_desc拼接比对）';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.PATIENT_ID IS '患者ID';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.QUEUE_TYPE IS '队列类型（筛选reserve）';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.IS_USED IS '是否使用（筛选used）';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.VISIT_DATE IS '冗余就诊日期';

-- 6. TR_OUTP_FIN_ACCT_MONEY - 结账支付方式明细（← outp_acct_money，bt7/bt9/bt10用）
CREATE TABLE TR_OUTP_FIN_ACCT_MONEY (
    ID                  NUMBER(19) PRIMARY KEY,
    ACCT_NO             VARCHAR2(64) NOT NULL,
    MONEY_TYPE          VARCHAR2(30),
    INCOME_AMOUNT       NUMBER(18,2),
    REFUNDED_AMOUNT     NUMBER(18,2),
    CREATE_TIME         DATE DEFAULT SYSDATE,
    UPDATE_TIME         DATE DEFAULT SYSDATE
);
COMMENT ON TABLE TR_OUTP_FIN_ACCT_MONEY IS '门诊财务报表-结账支付方式明细(bt7/bt9/bt10用)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MONEY.ACCT_NO IS '结账号(关联TR_OUTP_FIN_ACCT_MASTER)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MONEY.MONEY_TYPE IS '支付方式';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MONEY.INCOME_AMOUNT IS '收入金额';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MONEY.REFUNDED_AMOUNT IS '退费金额';

-- 表注释（原先误放在 18_住院预交金统计.sql，那些表在 18 执行时尚未创建）
COMMENT ON TABLE TR_OUTP_FIN_CLINIC_MASTER IS '门诊财务报表-就诊主表日快照';
COMMENT ON TABLE TR_OUTP_FIN_RCPT_ACCT IS '门诊财务报表-收据明细（人次去重、bt1/3/4/6/8）';
COMMENT ON TABLE TR_OUTP_FIN_ACCT_MASTER IS '门诊财务报表-结账汇总（收据张数/金额唯一口径）';
COMMENT ON TABLE TR_OUTP_FIN_PAYMENTS_MONEY IS '门诊财务报表-支付方式明细（bt5/7/9）';
COMMENT ON TABLE TR_OUTP_FIN_MOP_QUEUE IS '门诊财务报表-排班队列（bt2取号渠道分析）';

-- ------------------------------------------------------------------
-- 按 OutpatientFinanceMapper 实际引用补齐的列（原 DDL 缺失, 会让 bt1~bt12 全部报 ORA-00904）
-- ------------------------------------------------------------------
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.STAT_DATE IS '统计日期(所有查询的过滤列)';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.VISIT_NO IS '就诊号(关联 MOP_QUEUE 取号渠道)';
COMMENT ON COLUMN TR_OUTP_FIN_CLINIC_MASTER.IS_RETURN_TYPE IS '是否退号(1=正常就诊 计+1，-1=退号 计-1，见 OutpatientFinanceMapper 的净量口径)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.STAT_DATE IS '统计日期(所有查询的过滤列)';
COMMENT ON COLUMN TR_OUTP_FIN_RCPT_ACCT.TOTAL_COSTS IS '金额(bt8 业务类型金额口径)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.ACCT_NO IS '结账号(关联 TR_OUTP_FIN_ACCT_MONEY)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.STAT_DATE IS '统计日期(所有查询的过滤列)';
COMMENT ON COLUMN TR_OUTP_FIN_ACCT_MASTER.OPERATOR_NO IS '收费员号(bt6/bt11 渠道分析)';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.STAT_DATE IS '统计日期(与 CLINIC_MASTER 同日关联)';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.VISIT_NO IS '就诊号(与 CLINIC_MASTER.VISIT_NO 关联)';
COMMENT ON COLUMN TR_OUTP_FIN_MOP_QUEUE.SOURCE_NAME IS '取号来源名称(bt1 订单来源分析)';

-- 索引（同样由 18 迁入，必须在本文件的 CREATE TABLE 之后执行）
-- 按 mapper 的实际过滤/关联列调整: 过滤条件基本都落在 STAT_DATE, 关联键为 VISIT_NO / RCPT_NO / ACCT_NO
CREATE INDEX IDX_FIN_CLINIC_STAT ON TR_OUTP_FIN_CLINIC_MASTER(STAT_DATE);
CREATE INDEX IDX_FIN_CLINIC_VISIT ON TR_OUTP_FIN_CLINIC_MASTER(STAT_DATE, VISIT_NO);
CREATE INDEX IDX_FIN_RCPT_STAT ON TR_OUTP_FIN_RCPT_ACCT(STAT_DATE);
CREATE INDEX IDX_FIN_RCPT_PID_RCPT ON TR_OUTP_FIN_RCPT_ACCT(PATIENT_ID, RCPT_NO);
CREATE INDEX IDX_FIN_ACCT_STAT ON TR_OUTP_FIN_ACCT_MASTER(STAT_DATE);
CREATE INDEX IDX_FIN_ACCT_NO ON TR_OUTP_FIN_ACCT_MASTER(ACCT_NO);
CREATE INDEX IDX_FIN_PAY_RCPT ON TR_OUTP_FIN_PAYMENTS_MONEY(RCPT_NO);
CREATE INDEX IDX_FIN_PAY_MONEY_TYPE ON TR_OUTP_FIN_PAYMENTS_MONEY(MONEY_TYPE);
CREATE INDEX IDX_FIN_ACCT_MONEY_NO ON TR_OUTP_FIN_ACCT_MONEY(ACCT_NO);
CREATE INDEX IDX_FIN_QUEUE_VISIT ON TR_OUTP_FIN_MOP_QUEUE(STAT_DATE, VISIT_NO);
