server:
  port: 18089
  servlet:
    context-path: /

spring:
  application:
    name: reports-gateway
  profiles:
    active: dev

# 追踪号配置
reports:
  trace:
    # 追踪号前缀规则: 字母组合+数字, 如 YQ, WM
    prefix: "YQ"
    # 追踪号数字长度
    number-length: 9
    # 是否包含方括号
    include-brackets: false
  data:
    # 数据模式: mock(默认) / jdbc / mybatis-plus
    mode: mybatis-plus
  # 分页默认配置
  page:
    # 默认当前页码
    default-page: 1
    # 默认每页条数
    default-page-size: 10

# 日志配置
logging:
  level:
    com.reports: INFO
    com.reports.mapper: DEBUG

    # MyBatis
    org.apache.ibatis: INFO        # ✅ 不输出列信息
    org.mybatis: INFO

    # Spring
    org.springframework: INFO
    org.springframework.web: INFO

    # 根日志
    root: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - [%X{traceId}] [%X{seq}] %msg%n"

# MyBatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    banner: false
